// Code generated by go generate; DO NOT EDIT.
// This file was generated by genreset.go

package metrics


func (rs *ResetableStruct) Reset() {
	if rs == nil {
		return
	}
	rs.i = 0
	rs.str = ""
	if rs.strP != nil {
		*rs.strP = ""
	}
	rs.s = rs.s[:0]
	clear(rs.m)
	var rsInterface interface{} = ResetableStruct{}
	if resetter, ok := rsInterface.(interface{ Reset() }); ok && rs.child != nil {
		resetter.Reset()
	}
}
