// Code generated by go generate; DO NOT EDIT.
// This file was generated by genreset.go

package metrics

func (rs *Metrics) Reset() {
	if rs == nil {
		return
	}
	rs.ID = ""
	rs.MType = ""
	if rs.Delta != nil {
		*rs.Delta = 0
	}
	if rs.Value != nil {
		*rs.Value = 0
	}

}

func (rs *MetricsGroup) Reset() {
	if rs == nil {
		return
	}
	rs.Slice = rs.Slice[:0]

}

func (rs *AuditMetrics) Reset() {
	if rs == nil {
		return
	}
	rs.TS = 0
	rs.MetricNames = rs.MetricNames[:0]
	rs.IP = ""

}
