// Code generated by go generate; DO NOT EDIT.
// This file was generated by genreset.go

package metrics

func (s *Metrics) Reset() {
	if s == nil {
		return
	}
	s.ID = ""
	s.MType = ""
	if s.Delta != nil {
		*s.Delta = 0
	}
	if s.Value != nil {
		*s.Value = 0
	}

}

func (s *AuditMetrics) Reset() {
	if s == nil {
		return
	}
	s.TS = 0
	s.IP = ""

}

func (s *ResetableStruct) Reset() {
	if s == nil {
		return
	}
	s.i = 0
	s.str = ""
	if s.strP != nil {
		*s.strP = ""
	}

}
